<?php 

function church_inform_init(){
    drupal_add_css(drupal_get_path('module','church_inform').'/css/church_inform_style.css');
    drupal_add_js(drupal_get_path('module','church_inform').'/js/church_inform_jfunctions.js');
    
}


/** define Small Group node */
function church_inform_node_info() {
    return array(
        'smallgroup' => array(
            'name' => t('Small Group Form'),
            'base' => 'node_content',
            'has_title' => TRUE,
            'title_label' => t('Title'),
         )
    );
}

/*
function smallgroup_form($node, $form_state) {
    return node_content_form($node, $form_state);
}*/


function church_inform_menu(){
    $items = array();
    $items['custom/church_inform/index'] = array(
        'title'            => t('Custom module'),
        'page callback'    => 'church_inform_index_action',
        'access arguments' => array('access content'),
        'type'             => MENU_LOCAL_TASK,
    );

    //create new tab for the forms 
  
    //drupal_set_message($node->type);
    //$items['node/']
    //if($node->type=="smallgroup"){
    $items['node/%church_inform_menu/form'] = array(
        'title' => 'Form',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('add_fields_form', 1), //pass form_id
        //'access callback' => 'check_access',
        'access arguments' => array('adminiter users'), //accessible to admins
        'weight' => 1,
        'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
        //form_example.inc contains functions that builds and returns the $form array
        'file' => 'includes/components.inc',
        'type' => MENU_LOCAL_TASK,
    );

    $items['node/%church_inform_menu/submissions'] = array(
        'title' => 'Submissions',
        'page callback' => 'drupal_get_form',

        //form_example_1 is a function from form_example.inc file
        'page arguments' => array('form_example_1'), //pass form_id
        //'access callback' => 'addtab_access_callback',
        'access arguments' => array(1),
        'weight' => 1,
        'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
        //form_example.inc contains functions that builds and returns the $form array
        'file' => 'includes/form_example.inc',
        'type' => MENU_LOCAL_TASK,
    );

    $items['node/%church_inform_menu/form/discipleship'] = array(
        'title' => 'Discipleship Process',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('add_fields_form'), //pass form_id
        //'access callback' => 'addtab_access_callback',
        'access arguments' => array(1),
        'weight' => 1,
        //form_example.inc contains functions that builds and returns the $form array
        'file' => 'includes/components.inc',
        'type' => MENU_DEFAULT_LOCAL_TASK,
    );

    $items['node/%church_inform_menu/form/members'] = array(
        'title' => 'Member',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('add_member_form'), //pass form_id
        //'access callback' => 'addtab_access_callback',
        'access arguments' => array(1),
        'weight' => 1,
        'file' => 'includes/components.inc',
        'type' => MENU_LOCAL_TASK,
    );
    //}

    /*$items['node/%church_inform_menu/view'] = array(
        'page callback' => 'drupal_get_form',
        'page arguments' => array('add_fields_form'), //pass form_id
    );

    /*$items['node/%church_inform_menu/form/settings'] = array(
        'title' => 'Settings',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('form_example_1'), //pass form_id
        //'access callback' => 'addtab_access_callback',
        'access arguments' => array(1),
        'weight' => 1,
        //form_example.inc contains functions that builds and returns the $form array
        'file' => 'includes/form_example.inc',
        'type' => MENU_LOCAL_TASK,
    );*/
    

  return $items;
}

function church_inform_node_load($nodes, $types){

}

function check_access($node){
    $type= $node->type;
    

    drupal_set_message($type);
    if ($type=="smallgroup"){
        return TRUE; 
    }else{
        return FALSE;
    }
    /*if (user_is_logged_in()) {
        global $user;
        if (in_array('administrator', $user->roles) && ) {
            return TRUE;
        }
        foreach ($roles as $role) {
            if (in_array($role, $user->roles)) {
                return TRUE;
            }
        }
    }
    else {
        return FALSE;
    }*/
}

function church_inform_admin_paths(){
    $paths = array(
        'node/*/form' => TRUE,
        'node/*/form/*' => TRUE,
    );

    return $paths;
}

function church_inform_menu_load($nid){
    $node = node_load($nid);

    if (!is_numeric($nid)) { return FALSE; } 
    // Load the full node so that we can determine that it's the right 
    // content type. $node = node_load($nid); 
    // If the node has failed to load, or isn't the right content type, do not show. 
    

    //drupal_set_message($node->type);
    if ($node->type=='smallgroup') { 
        //return $node; 
    } 
}

function addtab_access_callback($node){
    //print node_type_get_name($type)."this";
    //if($node->type=='smallgroup'){
    //    return true & user_access('access_content');
    //}
    return true & user_access('access_content'); 
}


function church_inform_node_view($node, $view_mode, $langcode){
    $node->content['my_additional_field'] = array(
    '#markup' => "<p>Here's the additional content</p>",
    '#weight' => 10,
    '#theme' => 'mymodule_my_additional_field',
  );
}


function church_inform_theme(){      
    return array('church_inform_index' => array(
    'template' => 'church_inform_index'         
    )     
    ); 
} 

function church_inform_index_action(){
    return theme('church_inform_index', array()); 
}



